Chapter1,Chapter2,Chapter3,Chapter4 課題
YaKumagai/furiPHP_exercise pull request #2
Opened 2021-01-21 12:32 UTC by YaKumagai

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/01.md

https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/02.md

https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/03.md

https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/04.md

### 課題番号
課題1
課題2
課題3
課題4

### 現在の状況
一通り終わりました。
課題5は、これからです。
変数を間違えているところがあります
すいません。

### 期待していた動作

期待した動作になりました。
課題4_3は、思いのほか時間がかかりました。
var_dump($owners);
で、想像してみました。
arrayを変数に入れて次元を下げて値を取り出しました。

### 調べたこと・参考にしたURL
PHPふりがな

多次元配列と連想配列の組み合わせは、ネットから探し出すことが出来ません出した。

2021-01-21 23:56 UTC, kazu-taka requested changes
確認お願いします！

2021-01-21 23:56 UTC, kazu-taka commented on chap1_1.php
> +var_dump("本日の講師は".$teacher."です。");
@YaKumagai 
動作的には問題ありませんが、書籍と同じように、`=`の前後や`.`の前後に半角スペースを入れたほうが、変数や関数の存在が目立つので、全ての回答にスペースを入れるように修正お願いします✨

### 解答例

```php
<?php
var_dump("講師の名前は？");
$teacher = trim(fgets(STDIN));
var_dump("本日の講師は" . $teacher . "です。");
```

2021-01-21 23:56 UTC, kazu-taka commented on chap2_1.php
> +}elseif($age > 20){
@YaKumagai 
ここは上記2つの条件に当てはまらないものになるので、ただの `else`でOKです👍

2021-01-21 23:56 UTC, kazu-taka commented on chap2_2.php
> +}
@YaKumagai 
elseを通る値は無いようなきがしますがどうでしょうか！？
2で割りきれたら、偶数、それ以外は奇数の判定だけでOKです✨

2021-01-21 23:56 UTC, kazu-taka commented on chap2_3.php
> +}elseif($score_1 >= 80 || $score_2 >= 80){
@YaKumagai 
`入力した点数のうち、どちらかが50点以上80点未満 だったら、追試です。 と出力。`という問題になるので、今の条件ですと、「どちらかが80点以上なら追試」となってしまうため、0点と80点の場合でも追試になってしまう(本来は不合格)ので、修正お願いします🙏

2021-01-21 23:56 UTC, kazu-taka commented on chap3_2.php
> +    $aaa = $cnt+1;
@YaKumagai 
`$cnt +1`をせずに`range(1, 100)`でOKです👍

2021-01-21 23:56 UTC, kazu-taka commented on chap3_3.php
> +    }else{
@YaKumagai 
ここは`else`にせずに、`elseif`で続けて書いた方が、判定条件が並んで見やすくなるので、修正お願いします🙏

2021-01-21 23:56 UTC, kazu-taka commented on chap4_area.php
> +
@YaKumagai 
ここに空行を入れるよりは、`\n`で改行した方がコードが綺麗になるのでそちらの方が良いと思います✨

2021-01-21 23:56 UTC, kazu-taka commented on chap4_area.php
> +    echo $msg;
@YaKumagai 
関数は汎用性が高い方が良いので、ここでechoはせずただreturnさせて、呼び元で結果をecho した方が良いです✨

2021-01-21 23:56 UTC, kazu-taka commented on chap4_area.php
> +}
@YaKumagai 
こちらは使用していない関数なので、削除するようにお願いします✨

2021-01-21 23:56 UTC, kazu-taka commented on chap4_price.php
> +}
@YaKumagai 
displayMsg関数が作成されていないので、作成するようにお願いします✨
![スクリーンショット 2021-01-22 6 48 13](https://user-images.githubusercontent.com/5278718/105416671-d8a08d00-5c7d-11eb-805c-0a35337850cb.png)

2021-01-21 23:56 UTC, kazu-taka commented on chap4_price.php
> +    {$price}円(税込)になります。\n
@YaKumagai 
こちらの部分はdisplayMsgに移植願います✨

2021-01-21 23:56 UTC, kazu-taka commented on chap4_pet.php
> +$animal_types = $owner[["animal"][0]];
@YaKumagai 
1回目にdisplayMsgが呼ばれた時には、$ownerには斎藤さんの情報が入ってきます
`["name" => "斎藤", "animal" => ["猫", "猫", "猫"]]`
`$owner[["animal"][0]]`だと正しく値が取れていないような気がします。
$ownerのanimalの情報全てを取得してきて(斎藤さんの場合は`猫、猫、猫`)、countで件数を取得、array_uniqueで飼っているペットの種類を取得する必要があります。
`$owner['name']`と同じように、animalも取得するように修正お願いします✨

2021-01-22 03:03 UTC, kazu-taka approved these changes

2021-01-22 03:03 UTC, kazu-taka commented on chap2_3.php
> +}elseif($score_1 >= 80 || $score_2 >= 80){
@YaKumagai 
課題の説明は特に問題ありませんでした！

- 入力した点数2つがどちらも80点以上 だったら、 合格です。 と出力。
- 入力した点数のうち、どちらかが50点以上80点未満 だったら、追試です。 と出力。
- 入力した点数2つがどちらも50点未満 だったら、 不合格です。 と出力。

以下のようなパターンでテストした時に、同じ結果になればOKです！
```
数学 80点 国語 80点 合格
数学 80点 国語 79点 追試
数学 79点 国語 80点 追試
数学 49点 国語 80点 追試
数学 80点 国語 49点 追試
数学 50点 国語 50点 追試
数学 49点 国語 49点 不合格
```

ここの条件に当てはまらない場合、数学80点未満、国語80点未満は確定します。
```php
if ($score_1 >= 80 && $score_2 >= 80) {
    var_dump("合格です。");
```

次に判定すべき点は「入力した点数のうち、どちらかが50点以上80点未満」なので、80点未満は確定しているため、どちらかが50点以上かどうかを判定し、追試とします。
上記の条件にも当てはまらない場合は、どちらも50点未満が確定するので、不合格とします✨

2021-01-22 03:55 UTC, YaKumagai commented on chap2_2.php
> +}
はい、通る値は、私もないと思いますが、付けてみました。
削除します。

2021-01-22 03:55 UTC, YaKumagai commented on chap2_3.php
> +}elseif($score_1 >= 80 || $score_2 >= 80){
入力した点数2つがどちらも50点未満 だったら、 不合格です。 と出力。
国語、数学どちらも50点未満ということでしょうか

片方が、50点未満でしたら、不合格でしょうか？

2021-01-22 03:55 UTC, YaKumagai commented on chap4_area.php
> +    echo $msg;
$msg = <<<EOM
”ハロー！”
EOM;
echo $msg;
こちらは、呼び元で使えましたか？
うまく使えなかったので、もう一度やってみます。

2021-01-22 07:38 UTC, yukishimizumg reviewed
コメントしましたので、確認お願いします✨

2021-01-22 07:38 UTC, yukishimizumg commented on chap2_1.php
> +if($age < 20){
if文の書き方について、
`if と ( の間 に 1スペース` 、 `) と { の間 に 1スペース` 入れてください✨
以降同様に修正お願いします👍

```php
if ($age < 20) {
```

参考カリキュラム↓
https://github.com/elites-team/curriculum/blob/master/doc/06_php/study01/02.md
(P.073) : if文の書き方を覚えよう
【コードの書き方一部変更 : if について】

2021-01-22 07:38 UTC, yukishimizumg commented on chap2_1.php
> +}elseif($age === 20){
### (1) `===`と`==`の違い
今のコードでは、20と入力した場合に"成人です"と出力されてしまいます。
`===` はデータ型も比較します。
fgets(STDIN)で入力された`20`はstring型(文字型)なので、`20(int型 数値型)` とは別のものと判定され、
`$age === 20` の結果が false になってしまいます。
ここでは `==` を使いましょう✨

### (2) 書き方について
`elseifの前後` と `) と { の間`にスペースを入れてください✨
以降同様に修正お願いします👍

```php
} elseif ($age === 20) {
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap2_1.php
> +}else{
else の前後にスペースを入れてください✨
以降同様に修正お願いします👍

```php
} else {
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap2_2.php
> +if($nums === 1){
これでもOKですが、以下のように1行で済ませることもできます✨

```php
if ($num % 2 == 1) {
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap3_1.php
> +$blood_types = ["A","B","O","AB"];
`,`の後にスペースを入れてください✨

```php
$blood_types = ["A", "B", "O", "AB"];
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap3_1.php
> +foreach($blood_types as $blood_type){
foreachの書き方について、
`foreach と ( の間` に スペース、`) と { の間 ` に スペースを入れてください✨

```php
foreach ($blood_types as $blood_type) {
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap3_2.php
> +foreach(range(1,100) as $cnt){
rangeの書き方について、`, と100の間`にスペースを入れてください✨
foreachも上述と同様にスペースを適切に入れてください🙌
以降同様に修正お願いします！

```php
foreach (range(1, 100) as $cnt) {
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap4_1.php
> +require_once __DIR__."/chap4_area.php";
`.` の前後にスペースを入れましょう
以降も同様に修正お願いします✨

```php
require_once __DIR__ . "/chap4_area.php";
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap4_1.php
> +$msg = calcArea($top,$bottom,$height);
`,` の後にスペースを入れてください✨

```php
$msg = calcArea($top, $bottom, $height);
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap4_2.php
> +$sum = add($item1,$item2,$item3);
`,` の後にスペースを入れてください✨

2021-01-22 07:38 UTC, yukishimizumg commented on chap4_2.php
> +$msg = displayMsg($name,$sum,$price);
`,` の後にスペースを入れてください✨

2021-01-22 07:38 UTC, yukishimizumg commented on chap4_price.php
> +function add($item1,$item2,$item3){
functionの書き方について
`,` の後にスペースを入れてください✨
`) と { の間`にスペースを入れましょう！
以降同様に修正お願いします👍

```php
function add($item1, $item2, $item3) {
```

2021-01-22 07:38 UTC, yukishimizumg commented on chap4_pet.php
> +$animal = implode('、',array_unique($animal_types));
`,`の後ろにスペースを入れてください✨

```php
$animal = implode('、', array_unique($animal_types));
```

2021-01-22 11:16 UTC, yukishimizumg reviewed
1つコメント追加しました！
そちらを修正したらマージしてください🙆✨

2021-01-22 11:16 UTC, yukishimizumg commented on chap4_pet.php
> +$msg = <<<EOM
インデントを下げてください👍
(すみません、前回指摘漏れでした)

2021-01-22 12:15 UTC, merged